<?php
require_once dirname(__DIR__) . '/includes/bootstrap.php';
require_once dirname(__DIR__) . '/includes/helpers.php';
Auth::requireLogin();
Auth::requirePermission('billing.manage');

$receipt = Database::query('SELECT pay.*, i.invoice_no, i.total, i.paid, p.patient_no, CONCAT(p.first_name," ",p.last_name) patient_name, hp.name hospital_name, hp.address, hp.phone, hp.email FROM payments pay JOIN invoices i ON i.id=pay.invoice_id JOIN patients p ON p.id=i.patient_id CROSS JOIN hospital_profiles hp WHERE pay.id=? LIMIT 1', [$_GET['id'] ?? 0])->fetch();
if (!$receipt) {
    http_response_code(404);
    exit('Receipt not found');
}
$items = Database::query('SELECT * FROM invoice_items WHERE invoice_id=? ORDER BY id', [$receipt['invoice_id']])->fetchAll();

function pdf_text(string $text): string
{
    $text = str_replace(["\r", "\n"], ' ', $text);
    return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $text);
}

function pdf_money(mixed $amount): string
{
    return 'NGN ' . number_format((float) $amount, 2);
}

$content = [];
$content[] = '0.95 0.99 0.96 rg 0 0 595 842 re f';
$content[] = '0.18 0.62 0.41 rg 0 720 595 122 re f';
$content[] = '1 1 1 rg 42 760 72 42 re f';
$content[] = '0.18 0.62 0.41 rg BT /F2 24 Tf 60 772 Td (HMS) Tj ET';
$content[] = '1 1 1 rg BT /F2 20 Tf 132 790 Td (' . pdf_text($receipt['hospital_name']) . ') Tj ET';
$content[] = '1 1 1 rg BT /F1 10 Tf 132 772 Td (' . pdf_text($receipt['address']) . ') Tj ET';
$content[] = '1 1 1 rg BT /F1 10 Tf 132 756 Td (' . pdf_text($receipt['phone'] . ' | ' . $receipt['email']) . ') Tj ET';

$content[] = '0.18 0.62 0.41 rg 42 670 511 34 re f';
$content[] = '1 1 1 rg BT /F2 15 Tf 58 681 Td (OFFICIAL PAYMENT RECEIPT) Tj ET';
$content[] = '0.90 0.98 0.93 rg 418 676 98 20 re f';
$content[] = '0.18 0.62 0.41 rg BT /F2 12 Tf 440 682 Td (PAID) Tj ET';

$y = 635;
$rows = [
    ['Receipt No', $receipt['receipt_no']],
    ['Invoice No', $receipt['invoice_no']],
    ['Patient', $receipt['patient_no'] . ' - ' . $receipt['patient_name']],
    ['Payment Method', ucfirst(str_replace('_', ' ', $receipt['method']))],
    ['Payment Date', date('M j, Y h:i A', strtotime($receipt['paid_at']))],
];
foreach ($rows as [$label, $value]) {
    $content[] = '0.38 0.48 0.43 rg BT /F1 10 Tf 48 ' . $y . ' Td (' . pdf_text($label) . ') Tj ET';
    $content[] = '0.08 0.20 0.15 rg BT /F2 11 Tf 180 ' . $y . ' Td (' . pdf_text((string) $value) . ') Tj ET';
    $y -= 24;
}

$content[] = '0.18 0.62 0.41 rg 42 ' . ($y - 10) . ' 511 1.5 re f';
$y -= 36;
$content[] = '0.08 0.20 0.15 rg BT /F2 12 Tf 48 ' . $y . ' Td (Invoice Items) Tj ET';
$y -= 22;
$content[] = '0.90 0.98 0.93 rg 42 ' . ($y - 8) . ' 511 24 re f';
$content[] = '0.18 0.62 0.41 rg BT /F2 9 Tf 50 ' . $y . ' Td (Description) Tj ET';
$content[] = '0.18 0.62 0.41 rg BT /F2 9 Tf 385 ' . $y . ' Td (Qty) Tj ET';
$content[] = '0.18 0.62 0.41 rg BT /F2 9 Tf 455 ' . $y . ' Td (Total) Tj ET';
$y -= 24;

if (!$items) {
    $content[] = '0.38 0.48 0.43 rg BT /F1 10 Tf 50 ' . $y . ' Td (No invoice items recorded.) Tj ET';
    $y -= 22;
} else {
    foreach ($items as $item) {
        if ($y < 150) {
            break;
        }
        $content[] = '0.85 0.92 0.88 rg 42 ' . ($y - 8) . ' 511 1 re f';
        $content[] = '0.08 0.20 0.15 rg BT /F1 9 Tf 50 ' . $y . ' Td (' . pdf_text(substr($item['description'], 0, 58)) . ') Tj ET';
        $content[] = '0.08 0.20 0.15 rg BT /F1 9 Tf 385 ' . $y . ' Td (' . pdf_text((string) $item['quantity']) . ') Tj ET';
        $content[] = '0.08 0.20 0.15 rg BT /F1 9 Tf 455 ' . $y . ' Td (' . pdf_text(pdf_money($item['total'])) . ') Tj ET';
        $y -= 22;
    }
}

$content[] = '0.18 0.62 0.41 rg 345 96 208 52 re f';
$content[] = '1 1 1 rg BT /F1 10 Tf 362 125 Td (Amount Paid) Tj ET';
$content[] = '1 1 1 rg BT /F2 18 Tf 362 104 Td (' . pdf_text(pdf_money($receipt['amount'])) . ') Tj ET';
$content[] = '0.38 0.48 0.43 rg BT /F1 9 Tf 42 86 Td (Generated by HMS. Thank you for your payment.) Tj ET';

$stream = implode("\n", $content);
$objects = [];
$objects[] = '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj';
$objects[] = '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj';
$objects[] = '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >> endobj';
$objects[] = '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj';
$objects[] = '5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj';
$objects[] = '6 0 obj << /Length ' . strlen($stream) . ' >> stream' . "\n" . $stream . "\nendstream endobj";

$pdf = "%PDF-1.4\n";
$offsets = [0];
foreach ($objects as $object) {
    $offsets[] = strlen($pdf);
    $pdf .= $object . "\n";
}
$xref = strlen($pdf);
$pdf .= "xref\n0 " . (count($objects) + 1) . "\n0000000000 65535 f \n";
for ($i = 1; $i <= count($objects); $i++) {
    $pdf .= sprintf("%010d 00000 n \n", $offsets[$i]);
}
$pdf .= "trailer << /Size " . (count($objects) + 1) . " /Root 1 0 R >>\nstartxref\n{$xref}\n%%EOF";

header('Content-Type: application/pdf');
header('Content-Disposition: inline; filename="receipt-' . preg_replace('/[^A-Za-z0-9_-]/', '-', $receipt['receipt_no']) . '.pdf"');
echo $pdf;
